### ISSUE TITLE
Using lua-jump-to on ships with turrets renders turrets useless

### ISSUE THREAD

**Issue by Strygon** [FSO-Scripters/fso-scripts#23]
When making a ship (usually capital ships) jump to another point via lua-jump-to from AxInMissionJump, that ship doesn't use its turrets anymore. They don't turn and they don't fire anymore.

**Comment by wookieejedi** [comment]
Does ` lua-jump-to` issue a `play-dead-persistent` order?

**Comment by Goober5000** [comment]
@wookieejedi it issues a `play-dead` order...

```
	mn.runSEXP("( add-goal !" .. name .. "! ( ai-play-dead 101 ) )")
```

**Comment by Goober5000** [comment]
@Strygon does this work on RC3?

**Comment by Goober5000** [comment]
I'm pretty sure the issue that caused this bug was fixed in the aforementioned RC3.  In any case, I tested it with the latest source and it worked.
